/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ANKUR GUPTA' at '8/20/16 1:12 AM' with Gradle 3.0
 *
 * @author ANKUR GUPTA, @date 8/20/16 1:12 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
